In [1]:
import pandas as pd

<div>
<p></p>
<p>This tutorial uses the Titanic data set, stored as CSV. The data consists of the following data columns:</p>
<ul>
<li><p>PassengerId: Id of every passenger.</p></li>
<li><p>Survived: Indication whether passenger survived. <code>0</code> for yes and <code>1</code> for no.</p></li>
<li><p>Pclass: One out of the 3 ticket classes: Class <code>1</code>, Class <code>2</code> and Class <code>3</code>.</p></li>
<li><p>Name: Name of passenger.</p></li>
<li><p>Sex: Gender of passenger.</p></li>
<li><p>Age: Age of passenger in years.</p></li>
<li><p>SibSp: Number of siblings or spouses aboard.</p></li>
<li><p>Parch: Number of parents or children aboard.</p></li>
<li><p>Ticket: Ticket number of passenger.</p></li>
<li><p>Fare: Indicating the fare.</p></li>
<li><p>Cabin: Cabin number of passenger.</p></li>
<li><p>Embarked: Port of embarkation.</p></li>
</ul>
<p></p>
<a href="https://github.com/pandas-dev/pandas/raw/main/doc/data/titanic.csv">To raw data</a>
</div>

In [2]:
!curl https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv -o titanic.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 60080  100 60080    0     0   212k      0 --:--:-- --:--:-- --:--:--  213k

In [3]:
titanic = pd.read_csv("titanic.csv")

titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

<h1>How to calculate summary statistics</h1>

# <h2>Aggregating statistics</h2>

<img class="align-center" src="https://pandas.pydata.org/docs/_images/06_aggregate.svg">

### <h4>What is the average age of the Titanic passengers?</h4>

In [4]:
titanic["Age"].mean()

np.float64(29.69911764705882)

<p>Different statistics are available and can be applied to columns with numerical data. Operations in general exclude missing data and operate across rows by default.</p>

<img class="align-center" src="https://pandas.pydata.org/docs/_images/06_reduction.svg">

### <h4>What is the median age and ticket fare price of the Titanic passengers?</h4>

In [5]:
titanic[["Age", "Fare"]].median()

Age     28.0000
Fare    14.4542
dtype: float64

<p>The statistic applied to multiple columns of a <code>DataFrame</code> (the selection of two columns returns a <code>DataFrame</code>, see the <a href="https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html#min-tut-03-subset">subset data tutorial</a>) is calculated for each numeric column.</p>

<p>The aggregating statistic can be calculated for multiple columns at the same time. Remember the <code>describe</code> function from the <a href="https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#min-tut-01-tableoriented">first tutorial</a>?</p>

In [6]:
titanic[["Age", "Fare"]].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

<p>Instead of the predefined statistics, specific combinations of
aggregating statistics for given columns can be defined using the
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html#pandas.DataFrame.agg"><code>DataFrame.agg()</code></a> method:</p>

In [7]:
titanic.agg(
    {
        "Age": ["min", "max", "median", "skew"],
        "Fare": ["min", "max", "median", "mean"],
    }
)

              Age        Fare
min      0.420000    0.000000
max     80.000000  512.329200
median  28.000000   14.454200
skew     0.389108         NaN
mean          NaN   32.204208

<div>
<p><b>To user guide</b> Details about descriptive statistics are provided in the user guide section on <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-stats">descriptive statistics</a>.</p>
</div>

# <h2>Aggregating statistics grouped by category</h2>

<img class="align-center" src="https://pandas.pydata.org/docs/_images/06_groupby.svg">

### <h4>What is the average age for male versus female Titanic passengers?</h4>

In [8]:
titanic[["Sex", "Age"]].groupby("Sex").mean()

              Age
Sex
female  27.915709
male    30.726645

<p>As our interest is the average age for each gender, a subselection on
these two columns is made first: <code>titanic[["Sex", "Age"]]</code>. Next, the
<a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby" title="pandas.DataFrame.groupby"><code>groupby()</code></a> method is applied on the <code>Sex</code> column to make a group per category. The average age <em>for each gender</em> is calculated and returned.</p>
    
<p>Calculating a given statistic (e.g. <code>mean</code> age) <em>for each category in a column</em> (e.g.&nbsp;male/female in the <code>Sex</code> column) is a common pattern.
The <code>groupby</code> method is used to support this type of operations. This fits in the more general <code>split-apply-combine</code> pattern:</p>

<ul>
<li><p><strong>Split</strong> the data into groups</p></li>
<li><p><strong>Apply</strong> a function to each group independently</p></li>
<li><p><strong>Combine</strong> the results into a data structure</p></li>
</ul>

<p>The apply and combine steps are typically done together in pandas.</p>

<p>In the previous example, we explicitly selected the 2 columns first. If not, the <code>mean</code> method is applied to each column containing numerical columns by passing <code>numeric_only=True</code>:</p>

In [9]:
titanic.groupby("Sex").mean(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Sex,,,,,,,
female,431.028662,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818
male,454.147314,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893

<p>It does not make much sense to get the average value of the <code>Pclass</code>.
If we are only interested in the average age for each gender, the
selection of columns (rectangular brackets <code>[]</code> as usual) is supported on the grouped data as well:</p>

In [10]:
titanic.groupby("Sex")["Age"].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

<img class="align-center" src="https://pandas.pydata.org/docs/_images/06_groupby_select_detail.svg">

<div class="alert alert-block alert-info">
<p>Note</p>
<p>The <code>Pclass</code> column contains numerical data but actually represents 3 categories (or factors) with respectively the labels ‘1’, ‘2’ and ‘3’. Calculating statistics on these does not make much sense.
Therefore, pandas provides a <code>Categorical</code> data type to handle this type of data. More information is provided in the user guide <a href="https://pandas.pydata.org/docs/user_guide/categorical.html#categorical">Categorical data</a> section.</p>
</div>

### <h4>What is the mean ticket fare price for each of the sex and cabin class combinations?</h4>

In [11]:
titanic.groupby(["Sex", "Pclass"])["Fare"].mean()

Sex     Pclass
female  1         106.125798
        2          21.970121
        3          16.118810
male    1          67.226127
        2          19.741782
        3          12.661633
Name: Fare, dtype: float64

<p>Grouping can be done by multiple columns at the same time. Provide the column names as a list to the <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby" title="pandas.DataFrame.groupby"><code>groupby()</code></a> method.</p>

<div>
<p><b>To user guide</b> A full description on the split-apply-combine approach is provided in the user guide section on <a href="https://pandas.pydata.org/docs/user_guide/groupby.html#groupby">groupby operations</a>.</p>
</div>

# <h2>Count number of records by category</h2>

<img class="align-center" src="https://pandas.pydata.org/docs/_images/06_valuecounts.svg">

### <h4>What is the number of passengers in each of the cabin classes?</h4>

In [14]:
titanic["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

<p>The <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html#pandas.Series.value_counts" title="pandas.Series.value_counts"><code>value_counts()</code></a> method counts the number of records for each
category in a column.</p>
    
<p>The function is a shortcut, as it is actually a groupby operation in combination with counting of the number of records
within each group:</p>

In [15]:
titanic.groupby("Pclass")["Pclass"].count()

Pclass
1    216
2    184
3    491
Name: Pclass, dtype: int64

<div class="alert alert-block alert-info">
<p>Note</p>
<p>Both <code>size</code> and <code>count</code> can be used in combination with <code>groupby</code>. Whereas <code>size</code> includes <code>NaN</code> values and just provides the number of rows (size of the table), <code>count</code> excludes the missing values.
In the <code>value_counts</code> method, use the <code>dropna</code> argument to include or exclude the <code>NaN</code> values.</p>
</div>

<div>
<p><b>To user guide</b> The user guide has a dedicated section on <code>value_counts</code> , see the page on <a href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-discretization">discretization</a>.</p>
</div>

<div>
<h4>REMEMBER</h4><ul>
<li><p>Aggregation statistics can be calculated on entire columns or rows.</p></li>
<li><p><code>groupby</code> provides the power of the <em>split-apply-combine</em> pattern.</p></li>
<li><p><code>value_counts</code> is a convenient shortcut to count the number of entries in each category of a variable.</p></li>
</ul>
</div>

<div>
<p><b>To user guide</b> A full description on the split-apply-combine approach is provided in the user guide pages about <a href="https://pandas.pydata.org/docs/user_guide/groupby.html#groupby">groupby operations</a>.</p>
</div>