<h1>Summarise each group down to one row</h1>

<small>Source: <a href="https://github.com/tidyverse/dplyr/blob/pkgdown-v1.1.4/R/summarise.R"><code>R/summarise.R</code></a></small>
<div class="d-none name"><code>summarise.Rd</code></div>

<div>
<p><code>summarise()</code> creates a new data frame. It returns one row for each combination of grouping variables; if there are no grouping variables, the output will have a single row summarising all observations in the input. It will contain one column for each grouping variable and one column for each of the summary statistics that you have specified.</p>

<p><code>summarise()</code> and <code>summarize()</code> are synonyms.</p>
</div>

# <h2 id="ref-usage">Usage</h2>

<pre><code>summarise(.data, ..., .by = NULL, .groups = NULL)

summarize(.data, ..., .by = NULL, .groups = NULL)</code></pre></div>

# <h2 id="arguments">Arguments</h2>

<dl>

<dt id="arg--data">.data</dt>

<dd>
 
<p>A data frame, data frame extension (e.g. a tibble), or a lazy data frame (e.g. from dbplyr or dtplyr). See <em>Methods</em>, below, for more details.</p>

</dd>


<dt id="arg--">...</dt>

<dd>

<p>&lt;<code><a href="https://rlang.r-lib.org/reference/args_data_masking.html">data-masking</a></code>&gt; Name-value pairs of
summary functions. The name will be the name of the variable in the result.</p>

<p>The value can be:</p>

<ul>
<li><p>A vector of length 1, e.g. <code>min(x)</code>, <code><a href="https://dplyr.tidyverse.org/reference/context.html">n()</a></code>, or <code>sum(is.na(y))</code>.</p></li>
<li><p>A data frame, to add multiple columns from a single expression.</p></li>
</ul>

<p>Returning values with size 0 or &gt;1 was deprecated as of 1.1.0. Please use <code><a href="https://dplyr.tidyverse.org/reference/reframe.html">reframe()</a></code> for this instead.</p>

</dd>


<dt id="arg--by">.by</dt>

<dd>

<p>&lt;<code><a href="https://dplyr.tidyverse.org/reference/dplyr_tidy_select.html">tidy-select</a></code>&gt; Optionally, a selection of columns to group by for just this operation, functioning as an alternative to <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code>. For details and examples, see <a href="https://dplyr.tidyverse.org/reference/dplyr_by.html">?dplyr_by</a>.</p>

</dd>


<dt id="arg--groups">.groups</dt>

<dd>

<p>Grouping structure of the result.</p>

<ul>
<li><p>"drop_last": dropping the last level of grouping. This was the only supported option before version 1.0.0.</p></li>
<li><p>"drop": All levels of grouping are dropped.</p></li>
<li><p>"keep": Same grouping structure as <code>.data</code>.</p></li>
<li><p>"rowwise": Each row is its own group.</p></li>
</ul>

<p>When <code>.groups</code> is not specified, it is chosen based on the number of rows of the results:</p>

<ul>
<li><p>If all the results have 1 row, you get "drop_last".</p></li>
<li><p>If the number of rows varies, you get "keep" (note that returning a variable number of rows was deprecated in favor of <code><a href="https://dplyr.tidyverse.org/reference/reframe.html">reframe()</a></code>, which also unconditionally drops all levels of grouping).</p></li>
</ul>

<p>In addition, a message informs you of that choice, unless the result is ungrouped, the option "dplyr.summarise.inform" is set to <code>FALSE</code>, or when <code>summarise()</code> is called from a function in a package.</p>

</dd>

</dl>

# <h2 id="value">Value</h2>

<p>An object <em>usually</em> of the same type as <code>.data</code>.</p>

<ul>
<li><p>The rows come from the underlying <code><a href="https://dplyr.tidyverse.org/reference/group_data.html">group_keys()</a></code>.</p></li>
<li><p>The columns are a combination of the grouping keys and the summary expressions that you provide.</p></li>
<li><p>The grouping structure is controlled by the <code>.groups=</code> argument, the output may be another <a href="https://dplyr.tidyverse.org/reference/grouped_df.html">grouped_df</a>, a <a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a> or a <a href="https://dplyr.tidyverse.org/reference/rowwise.html">rowwise</a> data frame.</p></li>
<li><p>Data frame attributes are <strong>not</strong> preserved, because <code>summarise()</code> fundamentally creates a new data frame.</p></li>
</ul>

# <h2 id="useful-functions">Useful functions</h2>

<ul>
<li><p>Center: <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>, <code><a href="https://rdrr.io/r/stats/median.html">median()</a></code></p></li>
<li><p>Spread: <code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code>, <code><a href="https://rdrr.io/r/stats/IQR.html">IQR()</a></code>, <code><a href="https://rdrr.io/r/stats/mad.html">mad()</a></code></p></li>
<li><p>Range: <code><a href="https://rdrr.io/r/base/Extremes.html">min()</a></code>, <code><a href="https://rdrr.io/r/base/Extremes.html">max()</a></code>,</p></li>
<li><p>Position: <code><a href="https://dplyr.tidyverse.org/reference/nth.html">first()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/nth.html">last()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/nth.html">nth()</a></code>,</p></li>
<li><p>Count: <code><a href="https://dplyr.tidyverse.org/reference/context.html">n()</a></code>, <code><a href="https://dplyr.tidyverse.org/reference/n_distinct.html">n_distinct()</a></code></p></li>
<li><p>Logical: <code><a href="https://rdrr.io/r/base/any.html">any()</a></code>, <code><a href="https://rdrr.io/r/base/all.html">all()</a></code></p></li>
</ul>

# <h2 id="backend-variations">Backend variations</h2>

<p>The data frame backend supports creating a variable and using it in the same summary. This means that previously created summary variables can be
further transformed or combined within the summary, as in <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>.
However, it also means that summary variables with the same names as previous variables overwrite them, making those variables unavailable to later summary variables.</p>

<p>This behaviour may not be supported in other backends. To avoid unexpected results, consider using new names for your summary variables, especially when creating multiple summaries.</p>

# <h2 id="methods">Methods</h2>

<p>This function is a <strong>generic</strong>, which means that packages can provide implementations (methods) for other classes. See the documentation of individual methods for extra arguments and differences in behaviour.</p>

<p>The following methods are currently available in loaded packages: dbplyr (<code><a href="https://dbplyr.tidyverse.org/reference/summarise.tbl_lazy.html">tbl_lazy</a></code>), dplyr (<code>data.frame</code>, <code>grouped_df</code>, <code>rowwise_df</code>).</p>

# <h2 id="see-also">See also</h2>
<div><p>Other single table verbs:
<code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/reframe.html">reframe</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/select.html">select</a>()</code>,
<code><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a>()</code></p></div>

# <h2 id="ref-examples">Examples</h2>

In [3]:
library(tidyverse)

In [4]:
# A summary applied to ungrouped tbl returns a single row
mtcars |>
  summarise(mean = mean(disp), n = n())

  mean     n
1 230.7219 32

In [5]:
# Usually, you'll want to group first
mtcars |>
  group_by(cyl) |>
  summarise(mean = mean(disp), n = n())

  cyl mean     n
1 4   105.1364 11
2 6   183.3143  7
3 8   353.1000 14

In [9]:
# Each summary call removes one grouping level (since that group
# is now just a single row)
mtcars |>
  group_by(cyl, vs) |>
  summarise(cyl_n = n()) |>
  group_vars()

`summarise()` has grouped output by 'cyl'. You can override using the `.groups` argument.

[1] "cyl"

In [10]:
# BEWARE: reusing variables may lead to unexpected results
mtcars |>
  group_by(cyl) |>
  summarise(disp = mean(disp), sd = sd(disp))

  cyl disp     sd
1 4   105.1364 NA
2 6   183.3143 NA
3 8   353.1000 NA

In [11]:
# Refer to column names stored as strings with the `.data` pronoun:
var <- "mass"
summarise(starwars, avg = mean(.data[[var]], na.rm = TRUE))

  avg
1 97.31186

In [14]:
# In dplyr 1.1.0, returning multiple rows per group was deprecated in favor
# of `reframe()`, which never messages and always returns an ungrouped
# result:
mtcars |>
   group_by(cyl) |>
   summarise(qs = quantile(disp, c(0.25, 0.75)), prob = c(0.25, 0.75))

`summarise()` has grouped output by 'cyl'. You can override using the `.groups` argument.

  cyl qs     prob
1 4    78.85 0.25
2 4   120.65 0.75
3 6   160.00 0.25
4 6   196.30 0.75
5 8   301.75 0.25
6 8   390.00 0.75

In [15]:
mtcars |>
   group_by(cyl) |>
   reframe(qs = quantile(disp, c(0.25, 0.75)), prob = c(0.25, 0.75))

ERROR: Error in reframe(group_by(mtcars, cyl), qs = quantile(disp, c(0.25, 0.75)), : non trovo la funzione "reframe"