<h1><b>Joining Data</b></h1>
Combine data sources. Critical for almost all real-world data problems

# <h2 id="Introduction">Introduction</h2>

<p>You have the tools to obtain data from a single table in whatever format you want it. But what if the data you want is spread across multiple tables?</p>

<p>That's where <strong>JOIN</strong> comes in! <strong>JOIN</strong> is incredibly important in practical SQL workflows. So let's get started.</p

# <h2 id="Example">Example</h2>

<p>We'll use our imaginary <code>pets</code> table, which has three columns:</p>

<ul>
<li><code>ID</code> - ID number for the pet</li>
<li><code>Name</code> - name of the pet </li>
<li><code>Animal</code> - type of animal </li>
</ul>

<p>We'll also add another table, called <code>owners</code>.  This table also has three columns:</p>

<ul>
<li><code>ID</code> - ID number for the owner (different from the ID number for the pet)</li>
<li><code>Name</code> - name of the owner</li>
<li><code>Pet_ID</code> - ID number for the pet that belongs to the owner (which matches the ID number for the pet in the <code>pets</code> table)</li>
</ul>

<p><img src="https://storage.googleapis.com/kaggle-media/learn/images/Rx6L4m1.png"></p>

<p>To get information that applies to a certain pet, we match the <code>ID</code> column in the <code>pets</code> table to the <code>Pet_ID</code> column in the <code>owners</code> table.</p>
<p><img src="https://storage.googleapis.com/kaggle-media/learn/images/eXvIORm.png"></p>

<p>For example,</p>

<ul>
<li>the <code>pets</code> table shows that Dr. Harris Bonkers is the pet with ID 1. </li>
<li>The <code>owners</code> table shows that Aubrey Little is the owner of the pet with ID 1. </li>
</ul>

<p>Putting these two facts together, Dr. Harris Bonkers is owned by Aubrey Little.</p>

<p>Fortunately, we don't have to do this by hand to figure out which owner goes with which pet. In the next section, you'll learn how to use <strong>JOIN</strong> to create a new table combining information from the <code>pets</code> and <code>owners</code> tables.</p>

# <h2 id="JOIN" tabindex="0">JOIN</h2>

<p>Using <strong>JOIN</strong>, we can write a query to create a table with just two columns: the name of the pet and the name of the owner.</p>

<p><img src="https://storage.googleapis.com/kaggle-media/learn/images/fLlng42.png"></p>

<p>We combine information from both tables by matching rows where the <code>ID</code> column in the <code>pets</code> table matches the <code>Pet_ID</code> column in the <code>owners</code> table.</p>

<p>In the query, <strong>ON</strong> determines which column in each table to use to combine the tables.  Notice that since the <code>ID</code> column exists in both tables, we have to clarify which one to use.  We use <code>p.ID</code> to refer to the <code>ID</code> column from the <code>pets</code> table, and <code>o.Pet_ID</code> refers to the <code>Pet_ID</code> column from the <code>owners</code> table.</p>

<blockquote><p>In general, when you're joining tables, it's a good habit to specify which table each of your columns comes from. That way, you don't have to pull up the schema every time you go back to read the query.</p>
</blockquote>

<p>The type of <strong>JOIN</strong> we're using today is called an <strong>INNER JOIN</strong>. That means that a row will only be put in the final output table if the value in the columns you're using to combine them shows up in both the tables you're joining. For example, if Tom's ID number of 4 didn't exist in the <code>pets</code> table, we would only get 3 rows back from this query. There are other types of <strong>JOIN</strong>, but an <strong>INNER JOIN</strong> is very widely used, so it's a good one to start with.</p>

# <h2>Example: How many files are covered by each type of software license?</h2>

<p>GitHub is the most popular place to collaborate on software projects. A GitHub <strong>repository</strong> (or <strong>repo</strong>) is a collection of files associated with a specific project.</p>

<p>Most repos on GitHub are shared under a specific legal license, which determines the legal restrictions on how they are used.  For our example, we're going to look at how many different files have been released under each license.</p>

<p>We'll work with two tables in the database.  The first table is the <code>licenses</code> table, which provides the name of each GitHub repo (in the <code>repo_name</code> column) and its corresponding license.  Here's a view of the first five rows.</p>

In [2]:
from google.cloud import bigquery

# Authenticate
from google.colab import auth
auth.authenticate_user()

# Project ID
project_id = "burnished-road-363918"

# Create a "Client" object
client = bigquery.Client(project=project_id)

# Construct a reference to the "github_repos" dataset
dataset_ref = client.dataset("github_repos", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

# Construct a reference to the "licenses" table
licenses_ref = dataset_ref.table("licenses")

# API request - fetch the table
licenses_table = client.get_table(licenses_ref)

# Preview the first five lines of the "licenses" table
client.list_rows(licenses_table, max_results=5).to_dataframe()

                                           repo_name       license
0             autarch/Dist-Zilla-Plugin-Test-TidyAll  artistic-2.0
1                           thundergnat/Prime-Factor  artistic-2.0
2                       kusha-b-k/Turabian_Engin_Fan  artistic-2.0
3  onlinepremiumoutlet/onlinepremiumoutlet.github.io  artistic-2.0
4                       huangyuanlove/LiaoBa_Service  artistic-2.0

<p>The second table is the <code>sample_files</code> table, which provides, among other information, the GitHub repo that each file belongs to (in the <code>repo_name</code> column).  The first several rows of this table are printed below.</p>

In [3]:
# Construct a reference to the "sample_files" table
files_ref = dataset_ref.table("sample_files")

# API request - fetch the table
files_table = client.get_table(files_ref)

# Preview the first five lines of the "sample_files" table
client.list_rows(files_table, max_results=5).to_dataframe()

,repo_name,ref,path,mode,id,symlink_target
0,EOL/eol,refs/heads/master,generate/vendor/railties,40960,0338c33fb3fda57db9e812ac7de969317cad4959,/usr/share/rails-ruby1.8/railties
1,np/ling,refs/heads/master,tests/success/merger_seq_inferred.t/merger_seq...,40960,dd4bb3d5ecabe5044d3fa5a36e0a9bf7ca878209,../../../fixtures/all/merger_seq_inferred.ll
2,np/ling,refs/heads/master,fixtures/sequence/lettype.ll,40960,8fdf536def2633116d65b92b3b9257bcf06e3e45,../all/lettype.ll
3,np/ling,refs/heads/master,fixtures/failure/wrong_order_seq3.ll,40960,c2509ae1196c4bb79d7e60a3d679488ca4a753e9,../all/wrong_order_seq3.ll
4,np/ling,refs/heads/master,issues/sequence/keep.t,40960,5721de3488fb32745dfc11ec482e5dd0331fecaf,../keep.t

<p>Next, we write a query that uses information in both tables to determine how many files are released in each license.</p>

In [4]:
# Query to determine the number of files per license, sorted by number of files
query = """
        SELECT L.license, COUNT(1) AS number_of_files
        FROM `bigquery-public-data.github_repos.sample_files` AS sf
        INNER JOIN `bigquery-public-data.github_repos.licenses` AS L
            ON sf.repo_name = L.repo_name
        GROUP BY L.license
        ORDER BY number_of_files DESC
        """

# Set up the query (cancel the query if it would use too much of
# your quota, with the limit set to 10 GB)
safe_config = bigquery.QueryJobConfig(maximum_bytes_billed=10**10)
query_job = client.query(query, job_config=safe_config)

# API request - run the query, and convert the results to a pandas DataFrame
file_count_by_license = query_job.to_dataframe()

<p>It's a big query, and so we'll investigate each piece separately.</p>
<p><img src="https://storage.googleapis.com/kaggle-media/learn/images/QeufD01.png"></p>

<p>We'll begin with the <strong>JOIN</strong> (highlighted in blue above).  This specifies the sources of data and how to join them. We use <strong>ON</strong> to specify that we combine the tables by matching the values in the <code>repo_name</code> columns in the tables.</p>

<p>Next, we'll talk about <strong>SELECT</strong> and <strong>GROUP BY</strong> (highlighted in yellow).  The <strong>GROUP BY</strong> breaks the data into a different group for each license, before we <strong>COUNT</strong> the number of rows in the <code>sample_files</code> table that corresponds to each license.  (Remember that you can count the number of rows with <code>COUNT(1)</code>.)</p>

<p>Finally, the <strong>ORDER BY</strong> (highlighted in purple) sorts the results so that licenses with more files appear first.</p>

<p>It was a big query, but it gave us a nice table summarizing how many files have been committed under each license:</p>

In [5]:
# Print the DataFrame
file_count_by_license

         license  number_of_files
0            mit         20560894
1        gpl-2.0         16608922
2     apache-2.0          7201141
3        gpl-3.0          5107676
4   bsd-3-clause          3465437
5       agpl-3.0          1372100
6       lgpl-2.1           799664
7   bsd-2-clause           692357
8       lgpl-3.0           582277
9        mpl-2.0           457000
10       cc0-1.0           449149
11       epl-1.0           322255
12     unlicense           208602
13  artistic-2.0           147391
14           isc           118332